global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['eu-be.blitzhub.xyz:3000', 'na-be.blitzhub.xyz:3000']
        metrics_path: /metrics
        scrape_interval: 5s

      - job_name: 'database'
        static_configs:
          - targets: ['tokensdbeufe01:1521']
        metrics_path: /db-metrics
        scrape_interval: 10s

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq:15672']
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: 'solana'
        static_configs:
          - targets: ['solana-exporter:9834']
        metrics_path: /metrics
        scrape_interval: 10s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']

    rule_files:
      - "alerts.yml"

    alerts:
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 200
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage on Backend"
          description: "CPU usage on {{ $labels.instance }} exceeds 200% for more than 2 minutes."

      - alert: HighDatabaseQPS
        expr: database_queries_per_second > 900
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High Database QPS"
          description: "Database QPS on {{ $labels.instance }} exceeds 900 for more than 2 minutes."

      - alert: LargeRabbitMQQueue
        expr: rabbitmq_queue_messages > 500
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Large RabbitMQ Queue"
          description: "Queue size on {{ $labels.instance }} exceeds 500 messages for more than 2 minutes."
