-- Tokens Table
CREATE TABLE tokens (
    token_address VARCHAR2(44) PRIMARY KEY,
    name VARCHAR2(100),
    symbol VARCHAR2(10),
    current_supply NUMBER,
    total_supply NUMBER,
    market_cap NUMBER,
    volume_24h NUMBER,
    liquidity NUMBER,
    holders NUMBER,
    created_at TIMESTAMP
);

CREATE INDEX idx_tokens_created_at ON tokens(created_at);
CREATE INDEX idx_tokens_volume_24h ON tokens(volume_24h);

-- Fees Table
CREATE TABLE fees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_address VARCHAR2(44),
    fee_type VARCHAR2(20),
    amount NUMBER,
    timestamp TIMESTAMP
);

CREATE INDEX idx_fees_token_address ON fees(token_address);

-- UserBalances Table
CREATE TABLE UserBalances (
    user_address VARCHAR2(44),
    token_address VARCHAR2(44),
    balance NUMBER,
    PRIMARY KEY (user_address, token_address)
);

CREATE INDEX idx_userbalances_token ON UserBalances(token_address);

-- Transactions Table
CREATE TABLE Transactions (
    transaction_id VARCHAR2(64) PRIMARY KEY,
    token_address VARCHAR2(44),
    type VARCHAR2(10),
    total_usd NUMBER,
    amount NUMBER,
    price NUMBER,
    maker VARCHAR2(44),
    timestamp TIMESTAMP
);

CREATE INDEX idx_transactions_token ON Transactions(token_address);
CREATE INDEX idx_transactions_timestamp ON Transactions(timestamp);

-- PriceHistory Table
CREATE TABLE PriceHistory (
    token_address VARCHAR2(44),
    interval VARCHAR2(10),
    timestamp TIMESTAMP,
    open NUMBER,
    high NUMBER,
    low NUMBER,
    close NUMBER,
    volume NUMBER,
    PRIMARY KEY (token_address, interval, timestamp)
);

CREATE INDEX idx_pricehistory_token_interval ON PriceHistory(token_address, interval);

-- Users Table
CREATE TABLE Users (
    user_address VARCHAR2(44) PRIMARY KEY,
    username VARCHAR2(50),
    email VARCHAR2(100),
    created_at TIMESTAMP,
    last_login TIMESTAMP
);

CREATE INDEX idx_users_email ON Users(email);
