- name: Configurar Servidores Solana (SOL)
  hosts: eu-sol-01:as-sol-01
  become: yes
  tasks:
    - name: Instalar o cliente Solana (1.18.0)
      shell: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.18.0/install)"
      args:
        creates: /root/.local/share/solana/install

    - name: Adicionar Solana ao PATH
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"'
        state: present

    - name: Configurar Solana Node
      shell: |
        solana-validator --no-snapshot-fetch --rpc-port 8899 --max-slots-behind 100 --ledger /var/lib/solana
      args:
        creates: /var/lib/solana
      async: 3600
      poll: 0

    - name: Instalar Redis (7.2.0)
      apt:
        name: redis-server=7.2.0*
        state: present

    - name: Configurar Redis para cache de blockhashes
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^maxmemory '
        line: 'maxmemory 2GB'
      notify: Reiniciar Redis

    - name: Configurar Redis para append-only
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^appendonly '
        line: 'appendonly yes'
      notify: Reiniciar Redis

    - name: Configurar firewall (UFW) para SOL
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 8899  # Solana RPC
        - 8900  # Solana WebSocket
        - 6379  # Redis

    - name: Iniciar serviços
      systemd:
        name: redis-server
        enabled: yes
        state: started

  handlers:
    - name: Reiniciar Redis
      service:
        name: redis-server
        state: restarted
