- name: Configurar Ajustes Básicos para Todas as VMs
  hosts: all
  become: yes
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes essenciais
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - ufw
        - htop

    - name: Instalar Node Exporter (1.8.0) para monitoramento
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.8.0/node_exporter-1.8.0.linux-arm64.tar.gz
        tar xvf node_exporter-1.8.0.linux-arm64.tar.gz
        mv node_exporter-1.8.0.linux-arm64/node_exporter /usr/local/bin/
      args:
        creates: /usr/local/bin/node_exporter

    - name: Criar serviço Systemd para Node Exporter
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node-exporter.service
      notify: Reiniciar Node Exporter

    - name: Configurar UFW (permitir SSH)
      ufw:
        rule: allow
        port: 22

    - name: Habilitar UFW
      ufw:
        state: enabled

    - name: Iniciar Node Exporter
      systemd:
        name: node-exporter
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Reiniciar Node Exporter
      systemd:
        name: node-exporter
        state: restarted
