- name: Configurar Autonomous Database (TokensDB)
  hosts: localhost
  connection: local
  vars:
    oci_config_file: "~/.oci/config"
    accounts:
      - { profile: "EU-FE-01", region: "eu-frankfurt-1" }
      - { profile: "NA-FE-01", region: "us-ashburn-1" }
      # Adicione outras contas conforme necessário
    compartment_id: "ocid1.compartment.oc1..example"
  tasks:
    - name: Criar Autonomous Database para cada conta
      oci_database_autonomous_database:
        config_file_location: "{{ oci_config_file }}"
        config_profile_name: "{{ item.profile }}"
        compartment_id: "{{ compartment_id }}"
        display_name: "TokensDB{{ item.profile }}"
        db_name: "TokensDB{{ item.profile }}"
        cpu_core_count: 1
        data_storage_size_in_tbs: 1
        admin_password: "BlitzHub2025!"
        state: present
      loop: "{{ accounts }}"

    - name: Configurar esquemas e tabelas no Autonomous Database
      oci_database_autonomous_database_sql:
        config_file_location: "{{ oci_config_file }}"
        config_profile_name: "{{ item.profile }}"
        autonomous_database_id: "ocid1.autonomousdatabase.oc1..example{{ loop_index }}"
        sql_statements:
          - "CREATE TABLE tokens (mint VARCHAR2(44) PRIMARY KEY, name VARCHAR2(100), symbol VARCHAR2(10), market_cap NUMBER, volume_24h NUMBER, holders NUMBER, created_at TIMESTAMP)"
          - "CREATE TABLE fees (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token_mint VARCHAR2(44), fee_type VARCHAR2(20), amount NUMBER, timestamp TIMESTAMP)"
          - "CREATE INDEX idx_token_mint ON fees(token_mint)"
        state: present
      loop: "{{ accounts }}"
      loop_control:
        index_var: loop_index
